spring.application.name=authapp
server.servlet.context-path=/api/v1.0

spring.datasource.url=jdbc:mysql://localhost:3306/auth_app
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
jwt.secret.key=thisisthesecretkeyievercreatedinmydevelopmentcarrer
